@echo off
setlocal

REM Declare variables
echo Declaring variables...
set VMNAME=CVE-2018-15473-VM
set installed=not installed
set active=active at the moment
set enabled=not enabled at startup


REM Prompt user to start the script
echo Press a key when you are ready to start...
pause >nul

VBoxManage startvm "Router (Debian)" --type headless > nul

REM Creating the virtual machine
echo Starting script...
echo Creating VM...
VBoxManage createvm --name "%VMNAME%" --register

REM Modifying the virtual machine properties
echo Adding 2G of RAM...
VBoxManage modifyvm "%VMNAME%" --memory 2048 --cpus 2
echo Connect NIC: HostOnly...
VBoxManage modifyvm "%VMNAME%" --nic1 hostonly --hostonlyadapter1 "VirtualBox Host-Only Ethernet Adapter"
echo Connect NIC: NAT...
VBoxManage modifyvm "%VMNAME%" --nic2 nat

echo Adding storage controllers...
VBoxManage storagectl "%VMNAME%" --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage storagectl "%VMNAME%" --name "IDE Controller" --add ide

echo Attaching VBox Guest Additions ISO...
VBoxManage storageattach "%VMNAME%" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium "C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso"
echo Attaching VDI...
VBoxManage storageattach "%VMNAME%" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "C:/Users/simon/OneDrive - Hogeschool Gent/2023-2024/Semester 2/2. Cybersecurity & Virtualisation/10. NPE/VDI/1604.664/64bit/Ubuntu 16.04.6 (64bit).vdi"

echo Starting VM...
VBoxManage startvm "%VMNAME%"

echo Waiting for the VM to boot up...
timeout /t 45 /nobreak >nul

REM Interaction prompts for the user
echo Now you will need to enter some commands...
echo Please login to the VM with "osboxes.org"...
echo Press CTRL-ALT-T to open a terminal...
echo Enter "sudo su" and enter "osboxes.org"...
echo Enter "sudo echo 'osboxes ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"...
echo Enter "sudo bash /media/osboxes/VBox_GAs_7.0.10/autorun.sh"...
echo Please wait until the installation is completed, then press a key to continue the script...
pause >nul

echo The automatic script will now resume

REM Powering off the VM
echo Powering off the VM...
VBoxManage controlvm "%VMNAME%" poweroff >nul

echo Wait 5 seconds for the VM to shutdown...
timeout /t 5 /nobreak >nul

REM Adding a shared folder and restarting the VM
echo Adding the shared folder...
VBoxManage sharedfolder add "%VMNAME%" --name "sf_NPE" --hostpath "C:/Users/simon/OneDrive - Hogeschool Gent/2023-2024/Semester 2/2. Cybersecurity & Virtualisation/10. NPE" --automount
echo Powering up the VM (in headless mode)...
VBoxManage startvm "%VMNAME%" --type headless >nul

echo Waiting 1min for the VM to boot...
timeout /t 50 /nobreak >nul

REM Executing script on the VM
echo Copying the script from the shared folder to the user's home folder...
VBoxManage guestcontrol "%VMNAME%" run --exe "/usr/bin/sudo" --username osboxes --password osboxes.org --wait-stdout --wait-stderr -- -u root cp /media/sf_sf_NPE/script.sh /home/osboxes/script.sh
echo Adding the right permissions to execute the script...
VBoxManage guestcontrol "%VMNAME%" run --exe "/usr/bin/sudo" --username osboxes --password osboxes.org --wait-stdout --wait-stderr -- -u root chmod +x /home/osboxes/script.sh
timeout /t 5 /nobreak >nul

echo Running the next script...
timeout /t 5 /nobreak >nul
call "C:\Users\simon\OneDrive - Hogeschool Gent\2023-2024\Semester 2\2. Cybersecurity & Virtualisation\10. NPE\CVE2.bat"