@echo off
setlocal

pause >nul

REM Declare variables
set VMNAME=KALI-CVE
set PASTEBIN_URL=https://pastebin.com/raw/xwaq5CG9

REM Creating the virtual machine
echo Starting script...
echo Creating VM...
VBoxManage createvm --name "%VMNAME%" --register

REM Modifying the virtual machine properties
echo Adding 4G of RAM...
VBoxManage modifyvm "%VMNAME%" --memory 4096 --cpus 2
echo Connect NIC: HostOnly...
VBoxManage modifyvm "%VMNAME%" --nic1 hostonly --hostonlyadapter1 "VirtualBox Host-Only Ethernet Adapter"
echo Connect NIC: NAT...
VBoxManage modifyvm "%VMNAME%" --nic2 nat
echo Enabling Port forwarding...
VBoxManage modifyvm "%VMNAME%" --natpf2 "ssh,tcp,,2222,,22"

echo Adding storage controllers...
VBoxManage storagectl "%VMNAME%" --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage storagectl "%VMNAME%" --name "IDE Controller" --add ide

echo Attaching VBox Guest Additions ISO...
VBoxManage storageattach "%VMNAME%" --storagectl "IDE Controller" --port 0 --device 0 --type dvddrive --medium "C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso"
echo Attaching VDI...
VBoxManage storageattach "%VMNAME%" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "C:/Users/simon/OneDrive - Hogeschool Gent/2023-2024/Semester 2/2. Cybersecurity & Virtualisation/10. NPE/VDI/64bit/64bit/Kali Linux 2024.1 (64bit).vdi"

echo Starting VM...
VBoxManage startvm "%VMNAME%"

echo Wait for the VM to start...
timeout /t 45 /nobreak >nul

REM Interaction prompts for the user
echo Now you will need to enter some commands...
echo Please login to the VM with "osboxes" "osboxes.org"...
echo Press CTRL-ALT-T to open a terminal...
echo Enter "sudo su" and enter "osboxes.org"...
echo Enter "sudo echo 'osboxes ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"...
echo Enter "sudo systemctl start ssh", press a key to continue...
set /p IP_KALI=Enter the ip: 
pause >nul

echo The automatic script will now resume...

VBoxManage guestcontrol "CVE-2018-15473-VM" run --exe "/bin/bash" --username osboxes --password osboxes.org --wait-stdout --wait-stderr -- -c "ip a show enp0s3 | grep -oP 'inet \K[\d.]+'" > ip.txt 2>nul
for /f "delims=" %%a in (ip.txt) do set IP=%%a

echo The IP of the VM is %IP%, please remember...

echo We will now set up an ssh connection with the Kali VM...
echo You will have to enter "osboxes.org" to log in...
ssh -tt -o StrictHostKeyChecking=no -p 22 osboxes@%IP_KALI% "echo "%IP%" > ip.txt;sudo ip addr add 192.168.100.2/24 dev eth0;sudo systemctl enable ssh;wget -O scriptKali.sh %PASTEBIN_URL%;sudo dos2unix scriptKali.sh;sudo chmod +x scriptKali.sh;sudo bash scriptKali.sh;bash"
echo You can now press a key to leave this script and stop all VM's.
pause >nul
VBoxManage controlvm  "KALI-CVE" poweroff >nul
VBoxManage controlvm  "CVE-2018-15473-VM" poweroff >nul
